# AEGIS Project - Export StandardScaler params for ESP32
# This script rebuilds the scaler from your Wind Farm A pipeline
# and writes aegis_scaler_params.h with mean and std arrays.

import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

print("=== AEGIS: Exporting StandardScaler parameters ===")

base_dir = r"C:\Users\MOINODHEEN\Moinu\AEGIS_Project"

wind_farm_path = os.path.join(base_dir, "data", "Wind Farm A")
selected_ids = [25, 69, 68, 22]
event_labels_dict = {25: "normal", 69: "normal", 68: "anomaly", 22: "anomaly"}

all_data = []
all_labels = []

for event_id in selected_ids:
    event_path = os.path.join(wind_farm_path, "datasets", f"{event_id}.csv")
    print(f"Loading {event_path}")
    df = pd.read_csv(event_path, sep=";")

    label = 0 if event_labels_dict[event_id] == "normal" else 1
    numeric_df = df.select_dtypes(include=[np.number])
    sensor_cols = [
        col for col in numeric_df.columns
        if col not in ["asset_id", "id", "status_type_id"]
    ]

    all_data.append(numeric_df[sensor_cols])
    all_labels.extend([label] * len(df))

X_combined = pd.concat(all_data, ignore_index=True)
y_combined = np.array(all_labels)

print(f"Total samples: {len(X_combined):,}")
print(f"Number of sensor features: {len(sensor_cols)}")

# Fill NaNs and fit StandardScaler (same as training script)
X_combined = X_combined.fillna(X_combined.mean())
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_combined)

input_dim = X_scaled.shape[1]
print(f"Input dimension from scaler: {input_dim}")

if input_dim != 81:
    raise ValueError(f"Expected 81 features, got {input_dim}. Check data pipeline.")

means = scaler.mean_.astype(np.float32)
stds = scaler.scale_.astype(np.float32)

print("Scaler stats:")
print(f"  mean shape: {means.shape}")
print(f"  std shape:  {stds.shape}")

# Simple, safe formatter: one long line, no extra commas
def format_array(name, values):
    body = ", ".join(f"{v:.8f}f" for v in values)
    return f"const float {name}[{len(values)}] = {{\n  {body}\n}};\n"

mean_array_str = format_array("AEGIS_FEATURE_MEAN", means)
std_array_str  = format_array("AEGIS_FEATURE_STD", stds)

header_content = f"""// Auto-generated StandardScaler parameters for AEGIS Node 1
// Generated by export_scaler_params.py

#ifndef AEGIS_SCALER_PARAMS_H
#define AEGIS_SCALER_PARAMS_H

{mean_array_str}
{std_array_str}

#endif // AEGIS_SCALER_PARAMS_H
"""

out_path = os.path.join(
    base_dir,
    "Arduino_AEGIS",
    "AEGIS_Node1_TFLite",
    "AEGIS_Node1_TFLite",
    "aegis_scaler_params.h",
)

os.makedirs(os.path.dirname(out_path), exist_ok=True)

with open(out_path, "w") as f:
    f.write(header_content)

print("\nWritten header to:")
print(f"  {out_path}")
print("Done.")
